iZettle/izettle-toolbox

izettle-java/src/main/java/com/izettle/java/UUIDFactory.java, izettle-java/src/test/java/com/izettle/java/UUIDFactoryTest.java
Previously the method `createAlternative` mangled each byte in the UUID
without taking the structure of the data into consideration. The effect
of this was that the resulting alternative was not always a proper UUID
according to the standard.
This change does mainly two things:
* Make sure that `version` and `variant` is always preserved when
creating an alternative.
* For time-based UUID, the entire MSB is preserved as we want the
alternative to have the same time information as the original: only
the LSB is altered
ping @erikryverling , as you've been involved in the UUID stuff lately.
related to https://github.com/iZettle/izettle-planet/pull/321
=> UUIDFactory: Fixes create alternate

izettle-java/src/main/java/com/izettle/java/UUIDFactory.java, izettle-java/src/test/java/com/izettle/java/UUIDFactoryTest.java
Discovered when creating a test for backwards compatibility
Nice catch @mikaellothman ! This is all yours :) 
needs to be released and included in our other systems pronto before their release.
=> UUIDFactory: Fix for not preserving variant when createAlternative

izettle-emv/src/main/java/com/izettle/tlv/TLVDecoder.java, izettle-emv/src/test/java/com/izettle/tlv/TLVDecoderTest.java
Adds a strict mode to the decoder, which defaults disabled. Note that in strict mode zero paddings with even sizes will produce valid TLV object (T=00 L=00 V:null). Which is OK I guess...?
Ping @staffanjonsson @oskarwiksten
=> Add zero-padding parsing support in TLVDecoder.

izettle-messaging/src/main/java/com/izettle/messaging/QueueProcessingRunnable.java, izettle-messaging/src/main/java/com/izettle/messaging/QueueProcessingThread.java
* Extracts the body of the `run()` method from `QueueProcessingThread` into a new class `QueueProcessingRunnable` that only implements `Runnable` (and not `Thread`).
* This would be useful when running a queue poller in an environment where the caller would not want to create the actual thread manually, such as in a java EE environment.
=> messaging: Extract body of QueueProcessingThread into QueueProcessingRunnable

izettle-messaging/src/main/java/com/izettle/messaging/AmazonSNSSubscriptionSetup.java
* Adds class `AmazonSNSSubscriptionSetup` with a single public method `subscribeSQSQueueToSNSTopic` that sets up a SQS queue so that it receives all messages posted to a SNS topic.
* Requires the topic and queue to exist before creating the subscription.
* Sets up required permissions on the queue so that it can receive messages from the topic.
=> Add methods for setting up SQS subscription of a SNS topic

izettle-cassandra/pom.xml, izettle-messaging/pom.xml, izettle-messaging/src/main/java/com/izettle/messaging/MessagingException.java, izettle-messaging/src/main/java/com/izettle/messaging/QueueProcessor.java, pom.xml
For awhile now Amazon have split their SDK into separate jar's per
service, so we are picking only the services we use here (SNS, SQS and
EC2).
For your consideration:
@oskarwiksten, @mxns, @xiaodong-izettle and @mikaellothman
=> Upgrades AWS to v1.9.30 from v1.6.4

izettle-emv/src/main/java/com/izettle/msr/Track1Data.java, izettle-emv/src/test/java/com/izettle/msr/Track1DataTest.java
Basic track 1 parser that at least works for the MTIP and ADVT cards - will do some more testing with weird cards. Mostly to get the cardholder name for the last-used-email hashing, ref https://github.com/iZettle/izettle-planet/issues/138
Ping @linnie @staffanjonsson
=> Track 1 parser

izettle-messaging/src/main/java/com/izettle/messaging/AmazonSNSSubscriptionSetup.java
- A new queue has no policies, avoid NPE parsing nothing
On queue setup we attempt to append new policies to a queue. If the
queue is new it won't have any existing policies so we can start with
an empty list instead of attempting to parse policies that aren't
there.
This change avoids this exception:
Exception in thread "main" java.lang.IllegalArgumentException: JSON string cannot be null
at com.amazonaws.auth.policy.internal.JsonPolicyReader.createPolicyFromJsonString(JsonPolicyReader.java:66)
at com.amazonaws.auth.policy.Policy.fromJson(Policy.java:229)
at com.izettle.messaging.AmazonSNSSubscriptionSetup.allowSQSQueueToReceiveMessagesFromSNSTopic(AmazonSNSSubscriptionSetup.java:105)
at com.izettle.messaging.AmazonSNSSubscriptionSetup.subscribeSQSQueueToSNSTopic(AmazonSNSSubscriptionSetu …
=> Messaging: Avoids NPE on newly created queue setup

izettle-cart/pom.xml, izettle-cart/src/main/java/com/izettle/cart/Cart.java, izettle-cart/src/main/java/com/izettle/cart/CartUtils.java, izettle-cart/src/test/java/com/izettle/cart/CartTest.java, izettle-cart/src/test/java/com/izettle/cart/ItemTest.java, izettle-java/pom.xml, izettle-java/src/main/java/com/izettle/java/CollectionUtils.java, izettle-java/src/main/java/com/izettle/java/ResourceUtils.java, izettle-java/src/test/java/com/izettle/java/ArrayUtilsSpec.java, izettle-java/src/test/java/com/izettle/java/CollectionUtilsSpec.java
Nowadays the main source level of the toolbox is 1.8 (defined by it's parent pom).
However to prevent Android running into issues when using the toolbox we should set the source level of the used modules to 1.6
Ping @joezorry @silverpilen 
P.S Sorry for wall of types :wink:
=> Set source level of java and cart modules to 1.6

izettle-java/src/main/java/com/izettle/java/UUIDFactory.java, izettle-java/src/test/java/com/izettle/java/UUIDFactoryTest.java
As we're moving away from using the base64 representation of a `UUID`,
we still want to allow the old format in API's and as input parameters.
Testing for the two different versions everywhere makes the code ugly
and repetitive.
This change simply adds a parse method that will accept both versions of
the serialization format.
ping @niklas-izettle
=> UUIDFactory: Add method for parsing both string versions

izettle-messaging/pom.xml, izettle-messaging/src/main/java/com/izettle/messaging/serialization/JsonSerializer.java
For now, on version 2.5.1 of Jackson, we use the JSR310Module. That
will in a later upgrade be replaced by the JavaTimeModule(which
deprecates the JSR310Module).
Closes https://github.com/iZettle/izettle-toolbox/pull/137  
@nzroller
=> JsonSerializer: use Jackson java.time serialization module.

izettle-messaging/src/main/java/com/izettle/messaging/QueueServiceSender.java, izettle-messaging/src/test/java/com/izettle/messaging/QueueServiceSenderTest.java
Methods in QueueServiceSender now catch AmazonServiceException which might be thrown if Amazon-service is offline or URL is faulty.
Cleaned up test case for QueueServiceSender where EmptyBatchRequestException is never thrown.
Renamed test to better represent what it does.
=> Catch amazon service exception when sending batch to queue

izettle-java/pom.xml, izettle-java/src/main/java/com/izettle/java/CollectionUtils.java, izettle-java/src/main/java/com/izettle/java/ResourceUtils.java, izettle-java/src/main/java/com/izettle/java/TimeZoneId.java, izettle-java/src/test/java/com/izettle/java/ArrayUtilsSpec.java, izettle-java/src/test/java/com/izettle/java/CollectionUtilsSpec.java, izettle-java/src/test/java/com/izettle/java/TimeZoneIdTest.java, izettle-java/src/test/java/com/izettle/java/ValueChecksSpec.java
As we currently don't have any reasons to stay with java6 anymore.
Changed target version in pom
Switched to use diamond inference
Introduced `toZoneId` for easy access to the java8 zone object.
Also added 8 newcomers to the list of time zones: this covers all
current available zones in java8
ping @softarn
=> Izettle-java use java8

izettle-java/src/main/java/com/izettle/java/UUIDFactory.java, izettle-java/src/test/java/com/izettle/java/UUIDFactoryTest.java
Note: depends on #155 
This allows keeping the full resolution of the time information within a
UUID of type 1. Previously, limitations of the `Date` class prevented
resolution below milliseconds: now with `Instant` no time information is
lost, and a resolution down to 100ns is kept between creation and
parsing.
ping @erikryverling and @xiaodong-izettle : thoughts on this?
=> izettle-java uuid use instant instead of date

izettle-cart/src/main/java/com/izettle/cart/Cart.java, izettle-cart/src/main/java/com/izettle/cart/DiscountUtils.java, izettle-cart/src/main/java/com/izettle/cart/ItemUtils.java, izettle-cart/src/test/java/com/izettle/cart/CartTest.java
To get a clearer error thrown to the caller when construction fails.
Items with null for quantity previously generated this exception:
```
java.lang.NullPointerException: null
at com.izettle.cart.ItemUtils.getExactGrossValue(ItemUtils.java:53)
at com.izettle.cart.ItemUtils.getGrossValue(ItemUtils.java:22)
at com.izettle.cart.ItemUtils.getValue(ItemUtils.java:34)
at com.izettle.cart.CartUtils.getGrossValue(CartUtils.java:31)
at com.izettle.cart.Cart.<init>(Cart.java:36)
at com.izettle.cart.CartTest.itShouldThrowWhenItemsInvalid(CartTest.java:565)
```
After this change, this will be thrown:
```
java.lang.IllegalArgumentException: Item cannot have null quantity: TestItem{ unitPrice = 100, vatPercentage = 10.0, quantity = null, name = , discount = TestDiscount{ amount = 100, percentage = …
```
=> Cleanup: Validate items and discount early in constructor

izettle-java/src/main/java/com/izettle/java/Interval.java, izettle-java/src/test/java/com/izettle/java/IntervalTest.java
Unfortunately, the java8 time API doesn't have a proper interval class.
The only such classes in standard java is `Duration` and `Period`, but
they only hold information about the length of time: not the instant on
the timeline.
So, a proper interval class should really have been part of the standard
`java.time` API.
This class does that. It's a simple class consisting of two `Instant`s.
It's start inclusive, and end exclusive. Also, it has some utility
methods, such as `overlap`, `abuts` and `contains`.
ping @nzroller : thoughts on this? I'm thinking of quite a lot of facade methods where we're passing two `Date` objects around...
=> izettle-java Interval

izettle-java/src/main/java/com/izettle/java/InstantTruncator.java, izettle-java/src/test/java/com/izettle/java/InstantTruncatorSpec.java
`InstantTruncator`:
Unfortunately, the new java.time API doesn't allow for truncating units
larger than days, which is a show stopper for quite a few business
problems.
This utility class simply mimics the truncation behaviour of the
`CalendarTruncator` in the toolbox: just wrapping around an `Instant`
instead of a `Date`. Also, the `plus` and `minus` methods of `Instant`
also doesn't allow for units larger than a 24H, so those are added as
well for utility (so that the caller doesn't have to convert to a
`ZonedDateTime`).
ping @softarn and @aaanders : thoughts on this approach?
=> izettle-java instant truncator

izettle-java/src/main/java/com/izettle/java/ValueChecks.java, izettle-java/src/test/java/com/izettle/java/ValueChecksSpec.java
* Makes `ValueChecks.empty` return `true` when a value of `Optional.empty()` is passed as argument.
=> Consider `Optional.empty()` to be `ValueChecks.empty()`

izettle-messaging/src/main/java/com/izettle/messaging/serialization/MessageDeserializer.java, izettle-messaging/src/test/java/com/izettle/messaging/TestMessage.java, izettle-messaging/src/test/java/com/izettle/messaging/serialization/MessageDeserializerTest.java, izettle-messaging/src/test/resources/example-message-sent-with-messagepublisher-through-sns.json, izettle-messaging/src/test/resources/example-message-sent-with-messagepublisher-to-sqs.json, izettle-messaging/src/test/resources/example-message-sent-with-messagequeueproducer-to-sqs.json
* Makes the method `MessageDeserializer::removeSnsEnvelope` also remove SNS envelopes from messages that are produced by `QueueServiceSender::wrapInSNSMessage`.
* With this change, messages that are produced by either "regular" SNS publishing, directly to SQS by using `MessagePublisher`, and raw messages sent by `MessageQueueProducer`, will now all be correctly deserialized when being processed by a `MessageHandler`. Previously, messages sent directly to SQS by using `MessagePublisher` would not have their SNS envelopes removed when being handled by a `QueueServicePoller`.
=> Also remove SNS envelope from msgs produced by `wrapInSNSMessage`

izettle-java/src/main/java/com/izettle/java/UUIDFactory.java, izettle-java/src/test/java/com/izettle/java/UUIDFactoryTest.java
* Accept UUIDs as strings in either base64 or native format in method `createAlternative`.
* Overload method to accept uuids in format `java.util.UUID`.
=> Accept native UUID string format in `createAlternative`

izettle-messaging/pom.xml, izettle-messaging/src/main/java/com/izettle/messaging/serialization/JsonSerializer.java
ParameterNamesModule enables the use of reflection when deserializing
json string. Instead of explicitly annotating with jsonparameter annoations,
you can simply use @JsonCreator annotation on the constructor.
=> Register ParameterNamesModule so that @JsonCreator annotation works.

izettle-java/src/main/java/com/izettle/java/CollectionUtils.java, izettle-java/src/test/java/com/izettle/java/CollectionUtilsSpec.java
Fix a `NullPointerException` that I introduced in 6e46fd2 (#190). The old code used `StringBuilder#append`, which uses `String.valueOf` to translate `null` elements to "null". The new code used `Object#toString`, which obviously throws a `NullPointerException` for `null` elements.
`Objects.toString`, like `StringBuilder#append`, uses `String.valueOf`.
=> Fix NullPointerException in toString

izettle-messaging/src/main/java/com/izettle/messaging/QueueServiceSender.java, izettle-messaging/src/test/java/com/izettle/messaging/QueueServiceSenderTest.java
* Calls `sqs.sendMessage(SendMessageRequest)` when sending a single message through `QueueServiceSender`, instead of calling `sqs.sendMessageBatch` via `postBatch`
* Reason for changing is to have better handling of errors in case a single message fails.
Ping @xiaodong-izettle , how about this for solving the same issue that #192 intends to solve?
=> Use `sqs.sendMessage` for single message instead of `postBatch`

izettle-messaging/src/main/java/com/izettle/messaging/QueueServiceSender.java
* Specify the destination queue url when sending a single message through `MessagePublisher::post`.
* If not specifying the `queueUrl`, an exception of type `com.amazonaws.services.sqs.model.QueueDoesNotExistException` will be thrown when this is called.
* Bugfix for #193 .
Ping @xiaodong-izettle
=> Bugfix: Specify `queueURL` when sending single sqs message

izettle-emv/src/main/java/com/izettle/tlv/TLVDecoder.java, izettle-emv/src/test/java/com/izettle/tlv/TLVDecoderTest.java
* When checking a parsed TLV length, prevent input data from overflowing `Int.MAX_VALUE`.
* Prevents the following exception (as can be seen when running the unit-test `shouldDecodeTLVDataWithFourByteLengthOfAlmostIntMaxValue` added in this commit):
```
Stacktrace was: java.lang.OutOfMemoryError: Java heap space
at com.izettle.tlv.TLVDecoder.helper(TLVDecoder.java:99)
at com.izettle.tlv.TLVDecoder.decode(TLVDecoder.java:35)
at com.izettle.tlv.TLVDecoderTest.shouldDecodeTLVDataWithFourByteLengthOfAlmostIntMaxValue(TLVDecoderTest.java:200)
```
Ping @linnie @xiaodong-izettle
=> TLVDecoder: Prevent overflowing int when parsing TLV lengths

izettle-emv/src/main/java/com/izettle/tlv/TLVDecoder.java, izettle-emv/src/test/java/com/izettle/tlv/TLVDecoderTest.java
* Throw `TLVException` when parsing TLV data that specifies a negative length.
* Prevents the following exception, as can be seen when runnin ght unit-test `shouldDecodeTLVDataWithFourByteLengthThatOverflowsIntMaxValueToMinusOne` added in this commit):
```
Stacktrace was: java.lang.NegativeArraySizeException
at com.izettle.tlv.TLVDecoder.helper(TLVDecoder.java:99)
at com.izettle.tlv.TLVDecoder.decode(TLVDecoder.java:35)
at com.izettle.tlv.TLVDecoderTest.shouldDecodeTLVDataWithFourByteLengthThatOverflowsIntMaxValueToMinusOne(TLVDecoderTest.java:189)
```
Ping @linnie
=> TLVDecoder: Throw when parsing negative TLV lengths

izettle-dropwizard/src/main/java/com/izettle/dropwizard/cassandra/CassandraSessionFactory.java
The default consistency level from the driver is good enough for us... 
Also adding support to set `localDc` when creating cluster object...
Ping @x1a0, thanks...
=> Use default consistency level

izettle-java-alb/pom.xml, izettle-java-alb/src/main/java/com/izettle/alb/ALBAvailableInstancesCondition.java, izettle-java-alb/src/main/java/com/izettle/alb/ManagedALBRegistry.java, pom.xml
Instead of using the `AmazonElasticLoadBalancingClient`, the `AmazonElasticLoadBalancing` interface is used instead, which allows the user to build such an implementation using
```
AmazonElasticLoadBalancingClientBuilder.defaultClient();
```
which'll utilise any instance profiles and the region of the instance. 
@danizettle
=> Refactor to use minimal ELB interface to AWS

izettle-messaging/src/main/java/com/izettle/messaging/serialization/InstantRFC3339Module.java, izettle-messaging/src/main/java/com/izettle/messaging/serialization/JsonSerializer.java, izettle-messaging/src/test/java/com/izettle/messaging/TestMessageWithInstant.java, izettle-messaging/src/test/java/com/izettle/messaging/serialization/DefaultMessageSerializerTest.java, izettle-messaging/src/test/java/com/izettle/messaging/serialization/MessageDeserializerTest.java
Before this Instants got serialized as 2001-12-23T02:05:06.123Z 
instead of 2001-12 -23T02:05:06.123+0000
=> Serialize Instants in Rfc3339 format.

izettle-jackson/src/main/java/com/izettle/jackson/module/InstantRFC3339Module.java, izettle-jackson/src/test/java/com/izettle/jackson/module/InstantRFC3339ModuleTest.java
Ping @x1a0, thanks...
Background: we moved the Jackson serialisation stuff from `api-library` to here...
=> Fix timestamp deserialization issue.

izettle-jackson/src/test/java/com/izettle/jackson/module/InstantRFC3339ModuleTest.java
Even if the time is in even seconds.
Seems to pass. I still don't know what caused the absence of ms in our systems during the last couple of days.
Anyway, I thought that the test might be good to have in place anyway... ping @xiaodong-izettle
=> Instant serializer: Add test verifying presence of ms

izettle-jackson/pom.xml, izettle-jackson/src/main/java/com/izettle/jackson/paramconverter/UUIDParamConverterProvider.java, izettle-jackson/src/test/java/com/izettle/jackson/paramconverter/UUIDParamConverterProviderTest.java, pom.xml
Add a ParamConverterProvider for UUIDS that supports both standard hex format as well as base64.
This relates to thhis PR in cashregister-service. https://github.com/iZettle/cash-register/pull/170/files
As soon as this is merged I can release and bump the version for toolbox and use it in cash-register-service.
=> INT-290: Add UUIDParamConverterProvider

izettle-cart/src/main/java/com/izettle/cart/ItemLine.java
Used for getting the taxable value of a line before any VAT has been applied.
=> Added taxable value to ItemLine

izettle-cart/src/main/java/com/izettle/cart/ItemLine.java, izettle-cart/src/test/java/com/izettle/cart/ItemTest.java
Also change return type of `ItemLine::getActualTaxableValue` from `Long`
to `long` as it's always going to return a valid value, and the
convention in this project is to then use native types.
ping @psvanstrom
=> Cart: Add test for taxable value

izettle-dropwizard/pom.xml
Previous maven range was open-ended and made a new version break the build. This
change simply requires the allowed version to be strictly less than 3.2
=> Dependency mgmt: Exclude 3.2 from cassandra version

izettle-dropwizard/pom.xml, izettle-dropwizard/src/main/java/com/izettle/dropwizard/filters/AdminDirectAccessFilter.java, izettle-dropwizard/src/test/java/com/izettle/dropwizard/filters/AdminDirectAccessFilterTest.java
Allow access to `/admin` from localhost and from load balancer but not via a LB (from the outside)
by denying all access where header `X-ForwardedFor` is set. This filter is required when running a
DropWizard app on a single port.
=> Added AdminDirectAccessFilter to filter /admin access

izettle-emv/src/main/java/com/izettle/tlv/TLVDecoder.java, izettle-emv/src/test/java/com/izettle/tlv/TLVDecoderTest.java
* Throw explicit `TLVException` when reading the tag would otherwise exceed the buffer length.
* Prevents the following exception (as seen in the added unit test added in this commit):
```
java.lang.ArrayIndexOutOfBoundsException: 4
at com.izettle.tlv.TLVDecoder.helper(TLVDecoder.java:60)
at com.izettle.tlv.TLVDecoder.decode(TLVDecoder.java:35)
at com.izettle.tlv.TLVDecoderTest.shouldThrowExceptionOnMalformedTag(TLVDecoderTest.java:230)
```
* Reason for adding is to safeguard callers that only catch `TLVException` (and not `RuntimeException`s such as `ArrayIndexOutOfBoundsException`), so that callers also handle such malformed input correctly.
Ping @linnie
=> TLV Decoder: Fail early on malformed TLV tags

izettle-filters/pom.xml, izettle-filters/src/main/java/com/izettle/dropwizard/filters/AdminDirectAccessFilter.java, izettle-filters/src/test/java/com/izettle/dropwizard/filters/AdminDirectAccessFilterTest.java, pom.xml
Moves the admin filter to a new artifact `izettle-filters` with no
dependencies except for the servlet API.
The artifact `izettle-dropwizard` will be deprecated since it is not
widely used internally at iZettle (with the exception of the admin
filter).
=> Moves AdminDirectAccessFilter to izettle-filters

izettle-jackson/pom.xml, izettle-jackson/src/main/java/com/izettle/jackson/module/InstantRFC3339Module.java, izettle-jackson/src/main/java/com/izettle/jackson/paramconverter/InstantParam.java, izettle-jackson/src/test/java/com/izettle/jackson/paramconverter/InstantParamTest.java, izettle-java/src/main/java/com/izettle/java/DateTimeFormatters.java
So the need to have a way of receiving an `Instant` either via `@QueryParam` or `@PathParam` increases, so I present to you: `InstantParam`.
It's basically a wrapper around an Instant, which assumes the query string or path variable, is formatted into RFC3339 date time format.
Also added a convenience method to `DateFormatCreator` for creating a new jdk 8 `DateTimeFormatter` (instead of the old `DateFormat`), so now you can parse & format `TemporalAccessor`s!
=> InstantParam and a new DateTimeFormatter for RFC3339 formats

izettle-jackson/src/main/java/com/izettle/jackson/module/InstantRFC3339Module.java, izettle-jackson/src/main/java/com/izettle/jackson/paramconverter/InstantParam.java, izettle-jackson/src/test/java/com/izettle/jackson/paramconverter/InstantParamTest.java, izettle-java/src/main/java/com/izettle/java/DateTimeFormatters.java
So that it's identical to the `InstantRFC3339Module` in the sense that
it can also:
* parse strings using the Zulu indicator
* parse strings with none or parts of fractional seconds
* use 'uuuu' (year) instead of 'yyyy' (year-of-era) for serializing the
year
Sorry for modifying your code from yesterday @izrobin but I didn't really get your underlying reason for not making the parsing more forgiving, as in the `InstantRFC3339Module`. Making the two of them behave identical should be a goal, no?
Anyway, please have a look @izrobin
=> InstantParam: Improved parsing capabilities

izettle-jackson/src/main/java/com/izettle/jackson/module/InstantRFC3339Module.java, izettle-jackson/src/test/java/com/izettle/jackson/module/InstantRFC3339ModuleTest.java
The regular Date module for jackson can parse epoch longs as a Date.
Some entities has the epoch longs as the seriliazed version. These entities wont be able to use Instants transparently if
support for parsing epoch timestamps is not added.
=> Instants: let InstantRFC3339Module be able to parse epoch longs.

izettle-cart/src/main/java/com/izettle/cart/Cart.java, izettle-cart/src/test/java/com/izettle/cart/AlterationTest.java
Don't add residual discounts if the quantity is zero
Also adds a couple of tests, ensuring that this won't be a problem in different scenarios.
ping @vincenthauser
=> Cart: Fix for Zero quantity problem with discounts

izettle-cart/src/main/java/com/izettle/cart/Cart.java
Even the ones with quantity zero, as this serves as a helper for client
development when presenting consumed and available items for refunds.
as discussed @vincenthauser
=> Cart: `getAvailableItems` now returns the full list

izettle-java/src/main/java/com/izettle/java/InstantAdjusters.java, izettle-java/src/test/java/com/izettle/java/InstantAdjustersTest.java
Background:
Instants that are before and after a dst overlap got truncated differently.
Basically instants that where during the overlap period got truncated to the earlier offset, and those
that were after, to a later offeset.
This will prevent this, and will only truncate to the earliest possible offset.
=> BugFix: truncate to earliest Offset during DST overlap

izettle-java/src/main/java/com/izettle/java/ValueChecks.java, izettle-java/src/test/java/com/izettle/java/ValueChecksSpec.java, pom.xml
So the generic `assertNotEmpty` method doesn't work with primitive types, hence this addition.
We have a method called `boolean empty(object)` already, so let's also have this assertion method for it.
Also updated the pom to not include the dev gate repo urls
=> Introduce empty checks for primitive array types

izettle-java/src/main/java/com/izettle/java/ValueChecks.java
I messed up in my previous PR #241 ... Of course `Object` is not going to be passed into the method, but instead a generic `<T>`. Otherwise it wouldn't be useful at all.
Sorry for the inconvenience!
=> Change Object to generic T for assertNotEmpty

izettle-cassandra-datastax/pom.xml, izettle-jackson/pom.xml, pom.xml
Switched to mockito-core from legacy mockito-all
New versions
```
assertj-core.version - 3.8.0
bouncycastle.version - 1.58
netty.version - 4.1.17.Final
javax.servlet-api.version - 4.0.0
jackson.version - 2.9.2
javax-ws-rs.version - 2.1
google-truth.version - 0.36
cassandra.version - 2.2.11
aws.version - 1.11.229
metrics.version - 3.2.5
slf4j.version - 1.7.25
dropwizard.version - 1.2.0
jersey-common.version - 2.26
```
=> Bump dependencies

izettle-cassandra-astyanax/src/main/java/com/izettle/cassandra/AwsSecurityGroupHostSupplier.java, izettle-emv/src/main/java/com/izettle/tlv/TLVDecoder.java, izettle-emv/src/main/java/com/izettle/tlv/TLVEncoder.java, izettle-java/src/main/java/com/izettle/java/CollectionUtils.java
The @author does not really tell who is the actual creator behind the code, `git blame` is a better option.
This is the result of running the following on Linux:
find . -type f -name '*.java' -print0 | xargs -0 perl -0777 -pi -e 's|/\*\*[\s\*]+?\@author.+?\*/\n||sg'
find . -type f -name '*.java' -print0 | xargs -0 perl -0777 -pi -e 's|([\s\*]+?\@author.+?\n)+|\n|sg'
=> Remove @author javadoc

izettle-java/src/main/java/com/izettle/java/TimeZoneId.java
It seems newest JDK (8_162) changed ZoneId again, probably removed `Canada/East-Saskatchewan`.
Should we do this? Or try something else? Ping @adamvoncorswant. Thanks
=> Do not panic when Time ZoneId changed between JDKs.

izettle-java/src/main/java/com/izettle/java/TimeZoneId.java
It was removed from the JDK: http://mm.icann.org/pipermail/tz-announce/2017-October/000047.html
> Remove Canada/East-Saskatchewan from the 'backward' file, as it
exceeded the 14-character limit and was an unused misnomer anyway
Should be safe for us to remove as well since we haven't got any merchants in Canada.
=> Removed Canada/East-Saskatchewan from TimeZoneId

izettle-messaging/src/main/java/com/izettle/messaging/QueueProcessor.java, izettle-messaging/src/main/java/com/izettle/messaging/QueueServicePoller.java, izettle-messaging/src/main/java/com/izettle/messaging/QueueServiceSender.java, izettle-messaging/src/main/java/com/izettle/messaging/handler/MessageDispatcher.java, izettle-messaging/src/main/java/com/izettle/messaging/handler/MessageHandlerForSingleMessageType.java, izettle-messaging/src/main/java/com/izettle/messaging/serialization/MessageDeserializer.java, izettle-messaging/src/test/java/com/izettle/messaging/serialization/DefaultMessageSerializerTest.java, izettle-messaging/src/test/java/com/izettle/messaging/serialization/MessageDeserializerTest.java
Without this, one cannot customize the object mapper at all (in a good way).
For example, one might want to register KotlinModule or reuse the main object
mapper of the application.
I've tried not to be too intrusive and not break the API, so formatting and architecture stays the same (for good and for worse).
The gist of the PR is that the following static factory methods were overloaded with an `ObjectMapper objectMapper` parameter:
- `createQueueProcessor` (only for the single message type variants)
- `encryptedMessageDispatcher`
- `nonEncryptedMessageDispatcher`
- `encryptedMessageQueueConsumer`
- `nonEncryptedMessageQueueConsumer`
The old overloaded methods defaults to the `JsonSerializer.getInstance()` object mapper, to stay backwards compatible. I also renamed all variables called …
=> izettle-messaging: Allow custom object mapper

izettle-messaging/src/main/java/com/izettle/messaging/MessagePublisher.java, izettle-messaging/src/main/java/com/izettle/messaging/MessagePublisherWithAttributes.java, izettle-messaging/src/main/java/com/izettle/messaging/PublisherService.java, izettle-messaging/src/main/java/com/izettle/messaging/QueueServiceSender.java, izettle-messaging/src/test/java/com/izettle/messaging/PublisherServiceTest.java
This PR makes it possible to set the SQS attributes on messages. The attributes can be used to filter out messages on a more granular level than messageType.
This only adds support for filtering using SQS. Adding filtering on a programatic level would require some more work as we would like to do the filtering before we read the actual message.
An example where this would be useful is if you only want to listen to purchase messages that was created for the invoice checkout method. If we from the purchase service set an attribute called `checkout-method=invoice` the invoice-service could terraform to only listen to purchase messages that has that attribute/value combination on them - thus limiting the noise in the message handler.  
From the AWS doc:
Amazon SQS provides support for message …
=> Add support for setting attributes on messages in SQS

izettle-cart/README.md, izettle-cart/src/main/java/com/izettle/cart/AlterationCart.java, izettle-cart/src/main/java/com/izettle/cart/Cart.java, izettle-cart/src/main/java/com/izettle/cart/Discount.java, izettle-cart/src/main/java/com/izettle/cart/Item.java, izettle-cart/src/main/java/com/izettle/cart/ServiceCharge.java, izettle-cart/src/test/java/com/izettle/cart/AlterationTest.java
As it's misleading: re*fund* is about the financial consequence of a
product return, not about the shopping cart activity.
Using the de-facto standard naming of 'return' instead.
ping @joaxand : it's at least a start :)
=> Cart: Cleanup - Remove 'refund' as expression

izettle-cart/src/main/java/com/izettle/cart/DiscountUtils.java, izettle-cart/src/test/java/com/izettle/cart/CartTest.java
When a discount is invalid, this change does so that a descriptive
IllegalArgumentException is thrown rather than a hard-to-understand
NullPointerException
ping @xiaodong-izettle
=> Cart: Better exception handling

izettle-cassandra-datastax/pom.xml, izettle-cassandra-datastax/src/main/java/com/izettle/cassandra/paging/PagingContext.java, izettle-cassandra-datastax/src/main/java/com/izettle/cassandra/paging/PagingData.java, izettle-cassandra-datastax/src/main/java/com/izettle/cassandra/paging/PagingFactory.java, izettle-cassandra-datastax/src/main/java/com/izettle/cassandra/paging/PagingInput.java, izettle-cassandra-datastax/src/main/java/com/izettle/cassandra/paging/PagingResult.java, izettle-cassandra-datastax/src/main/java/com/izettle/cassandra/paging/PagingUrlBuilder.java, izettle-cassandra-datastax/src/test/java/com/izettle/cassandra/paging/Car.java, izettle-cassandra-datastax/src/test/java/com/izettle/cassandra/paging/CarAccessor.java, izettle-cassandra-datastax/src/test/java/com/izettle/cassandra/paging/PagingTest.java, pom.xml
Added Paging to be used for both Datastax mappers and manual mapping providing a Function that maps Row to an Java POJO.
There's two main usecases:
1) Paging responses for endpoints. PR also contain tool to set Link on response
2) Iterate over an statement and Consume result. GDRP upload for example.
https://izettle.atlassian.net/browse/SF-1713
=> Generic paging support for Datastax drivers

izettle-filters/README.md, izettle-filters/src/main/java/com/izettle/dropwizard/filters/AdminContextPathEnforcer.java, izettle-filters/src/main/java/com/izettle/dropwizard/filters/AdminDirectAccessBundle.java, izettle-filters/src/test/java/com/izettle/dropwizard/filters/AdminContextPathEnforcerTest.java
- If set to /system: Do nothing
- If set to something else: Throw
- If not set at all: Set it to /system
This removes the need for any config changes for services --
all they need is the bundle. This is an enabler towards having
an iZettle Dropwizard flavor, with all necessary config,
that works OOTB.
=> Enforce that adminContextPath is set to /system

izettle-cart/src/test/java/com/izettle/cart/AlterationTest.java, izettle-kotlin/pom.xml, izettle-kotlin/src/main/kotlin/com/izettle/kotlin/Optionals.kt, izettle-kotlin/src/main/kotlin/com/izettle/kotlin/ValueChecks.kt, izettle-kotlin/src/test/kotlin/com/izettle/kotlin/OptionalsTest.kt, izettle-kotlin/src/test/kotlin/com/izettle/kotlin/ValueChecksTest.kt, pom.xml
This PR introduces a new `izettle-kotlin` library into the toolbox. The motivation for this library is simply to make programming in Kotlin at iZettle easier and more enjoyable, and to reduce boilerplate and ceremony (a primary goal of Kotlin)
Initially, I have provided some functions that I think will make our Kotlin code more "Kotlin-like", by encouraging chains of calls and not `if` statements. We are already using the `whenNotNull` function in https://github.com/iZettle/online-payment and it would be much better to have it in a library like this one.
Here is a summary of the features this PR will provide:
```kotlin
// Introduces a whenNoneNull() global function that acts like a multi-variable ?.let()
// Supports between 2 and 9 arguments of different or same types …
```
=> Introduces izettle-kotlin library

pom.xml
Accidentally merged with bad basepom 1.25 (which has broken spotbugs support)
=> Bump to basepom 1.26
