iZettle/izettle-toolbox

izettle-cart/src/main/java/com/izettle/cart/Cart.java
izettle-cart/src/main/java/com/izettle/cart/DiscountLine.java
izettle-cart/src/main/java/com/izettle/cart/ItemLine.java

ping @adamvoncorswant 
Tested locally via Android

Cart: Make stuff serializable

---

izettle-java/src/main/java/com/izettle/java/ResourceUtils.java
pom.xml

And introduce checkstyle braces check
ping @erikryverling

Dependency Mgmt: Bump izettle-maven to 1.5

---

izettle-jdbi/pom.xml
izettle-jdbi/src/main/java/com/izettle/jdbi/EnumNameBinder.java
izettle-jdbi/src/main/java/com/izettle/jdbi/InstantArgumentFactory.java
izettle-jdbi/src/main/java/com/izettle/jdbi/NotNullableContainerFactory.java
izettle-jdbi/src/main/java/com/izettle/jdbi/exception/NoResultException.java

Classes added:
* EnumNameBinder
* InstantArgumentFactory
* NotNullableContainerFactory
Also updated jdbi version in pom.xml
ping @erikryverling

Added common classes to jdbi

---

izettle-messaging/src/main/java/com/izettle/messaging/AmazonSNSSubscriptionSetup.java

Ping @iZettle/tx-team, thanks. 
I'll make a release after this gets merged...

Always append SQS permission settings rather than overwriting.

---

izettle-messaging/src/main/java/com/izettle/messaging/AmazonSNSSubscriptionSetup.java

- Use interfaces Amazon{SNS,SQS} rather than concrete asynchronous
implementations for subscription setup
We more likely want a synchronous subscription setup rather than
asynchronous so this change gives us the possibility of passing in a
regular client.
Ping @xiaodong-izettle

Uses Amazon{SNS,SQS} in subscription setup

---

izettle-java/src/main/java/com/izettle/java/UUIDFactory.java

* Create uuids as java.util.UUID

Expose more uuid utility functions

---

izettle-messaging/src/main/java/com/izettle/messaging/QueueProcessor.java

Ping @iZettle/transactions, thanks.

Enable asynchronous message handling.

---

izettle-cassandra/src/main/java/com/izettle/cassandra/SequenceGenerator.java

Semaphores have been added in order to decrease the number of concurrent
attempts to acquire distributed lock in Cassandra before sequence update.

Adds semaphores to sequence generator.

---

izettle-cart/src/main/java/com/izettle/cart/Cart.java
izettle-cart/src/main/java/com/izettle/cart/CartUtils.java
izettle-cart/src/main/java/com/izettle/cart/ServiceCharge.java
izettle-cart/src/main/java/com/izettle/cart/ServiceChargeLine.java
izettle-cart/src/test/java/com/izettle/cart/CartTest.java
izettle-cart/src/test/java/com/izettle/cart/ItemTest.java
izettle-cart/src/test/java/com/izettle/cart/TestServiceCharge.java

* A service charge can either be fixed amount or a percentage applied on the final value of cart.
* It can also belong to its own vatGroupi

Introduce ServiceCharge.

---

izettle-cart/src/main/java/com/izettle/cart/Cart.java
izettle-cart/src/main/java/com/izettle/cart/CartUtils.java
izettle-cart/src/main/java/com/izettle/cart/ItemUtils.java

* Add `final` wherever possible, and change the code to reduce reassignments
* Remove unecessary method
Just cosmetic changes, no logic is supposedly changed: all tests classes are
left completely untouched
ping @MrShish : this might a tad too religious, but I kinda like it this way :)

Cart: Misc Cleanup

---

izettle-messaging/pom.xml
izettle-messaging/src/main/java/com/izettle/messaging/handler/MeteredMessageHandler.java
pom.xml

Adds a metered message handler that can be used to push metrics to
a MetricsRegistry.
Ping @iZettle/platform

Adds metered message handler.

---

izettle-cart/src/test/java/com/izettle/cart/CartTest.java
izettle-cart/src/test/java/com/izettle/cart/ItemTest.java
izettle-cassandra/pom.xml
izettle-cassandra/src/test/java/com/izettle/cassandra/DeterministicTimeUUIDFactoryTest.java
izettle-cassandra/src/test/java/com/izettle/cassandra/TimeSeriesIT.java
izettle-java/src/test/java/com/izettle/java/ResourceUtilsTest.java
izettle-jdbi/src/test/java/com/izettle/jdbi/PostgresArrayArgumentSpec.java
izettle-jdbi/src/test/java/com/izettle/jdbi/SqlArraySpec.java
izettle-messaging/src/test/java/com/izettle/messaging/QueueServicePollerTest.java
izettle-messaging/src/test/java/com/izettle/messaging/QueueServiceSenderTest.java
pom.xml

Ping @nzroller and @mikaellothman, thanks.

Upgrade astyanax for cassandra upgrading.

---

izettle-messaging/src/main/java/com/izettle/messaging/QueueProcessor.java

QueueProcessor improvement.

---

izettle-cart/src/main/java/com/izettle/cart/CartUtils.java
izettle-cart/src/main/java/com/izettle/cart/ServiceChargeLine.java
izettle-messaging/src/main/java/com/izettle/messaging/MessagingException.java
pom.xml

To get the latest checkstyle rules:
* Comma(,) at end of line
* Plus(+) and dot(.) at beginning of line.
* All files should have an NL at end of file
ping @nzroller again: did I get it right with the oss pom?

Checkstyle: Bump oss basepom to 1.9

---

izettle-cryptography/src/main/java/com/izettle/cryptography/KeyUtil.java
izettle-cryptography/src/main/java/com/izettle/cryptography/PGP.java
pom.xml

Ping @nzroller and @staffanjonsson, thanks.

upgrade bouncycastle to 1.47 to 1.52

---

izettle-cart/pom.xml
izettle-cart/src/main/java/com/izettle/cart/Cart.java
izettle-cart/src/main/java/com/izettle/cart/CartUtils.java
izettle-cart/src/main/java/com/izettle/cart/ItemUtils.java
izettle-emv/pom.xml
izettle-emv/src/main/java/com/izettle/tlv/ArrayUtils.java
izettle-emv/src/main/java/com/izettle/tlv/Hex.java
izettle-emv/src/main/java/com/izettle/tlv/TLV.java
izettle-emv/src/main/java/com/izettle/tlv/TLVDecoder.java
izettle-emv/src/main/java/com/izettle/tlv/TLVUtils.java
izettle-emv/src/test/java/com/izettle/tlv/ArrayUtilsSpec.java
izettle-emv/src/test/java/com/izettle/tlv/HexSpec.java
izettle-emv/src/test/java/com/izettle/tlv/TLVDecoderTest.java
izettle-emv/src/test/java/com/izettle/tlv/TLVEncoderTest.java

As that project will start using java8 features, and these projects are
used by the android platform.
ping @softarn perhaps?

Dependency Mgmt: Remove izettle-cart and izettle-emv's dependency on izettle-java

---

izettle-cassandra/src/main/java/com/izettle/astyanax/impl/AwsSecurityGroupHostSupplier.java
izettle-cassandra/src/main/java/com/izettle/cassandra/SchemaVersionUpdater.java
izettle-cryptography/src/main/java/com/izettle/cryptography/PGP.java
izettle-emv/src/main/java/com/izettle/tlv/TLV.java
izettle-java/src/main/java/com/izettle/java/CalendarTruncator.java
izettle-java/src/main/java/com/izettle/java/ResourceUtils.java
izettle-java/src/test/java/com/izettle/java/ResourceUtilsTest.java
izettle-jdbi/src/main/java/com/izettle/jdbi/PostgresArrayArgumentFactory.java
izettle-messaging/src/main/java/com/izettle/messaging/QueueProcessingRunnable.java
izettle-messaging/src/main/java/com/izettle/messaging/handler/MeteredMessageHandler.java
izettle-messaging/src/main/java/com/izettle/messaging/serialization/MessageDeserializer.java

Findbugs reports a number of resourceleaks where resources are not being closed on every execution path.
Adding try-with-resources to those it reports to stop resource leaks.
/cc @mxns + @jakanjakan

Use try-with-resources idiom on autocloseables

---

izettle-jdbi/src/main/java/com/izettle/jdbi/PostgresArrayArgumentFactory.java
izettle-jdbi/src/test/java/com/izettle/jdbi/PostgresArrayArgumentFactoryTest.java

Unit test was missing for the build method.
/cc @mxns

Add unit test for SqlArrayFactory

---

izettle-messaging/pom.xml
izettle-messaging/src/main/java/com/izettle/messaging/serialization/JsonSerializer.java
pom.xml

Add Jdk8Module to JsonSerializer to support JDK8 Jackson Serialization

Add support for JDK8 serialization

---

izettle-java/src/main/java/com/izettle/java/Interval.java
izettle-java/src/test/java/com/izettle/java/IntervalTest.java

Since this is closely related to the java time package I think we should follow their convention with `of` methods for instantiation.

Java8ify interval

---

izettle-messaging/src/main/java/com/izettle/messaging/QueueServiceSender.java

* Adds factory method in `QueueServiceSender` to create an encrypted version of a `MessagePublisher`.
* Reason for adding is that all of the support is already in place for encrypting messages when sending through a `MessagePublisher`, similar to what is available when using a `MessageQueueProducer<T>`.
* Long-term plan with this addition is to deprecate `MessageQueueProducer<T>` and instead only use `MessagePublisher`, since they are so similar and share almost the same responsibility. It is not clear for all callers what the difference between these two classes are, so having just one would simplify for callers.

Add factory method for creating encrypted MessagePublisher

---

izettle-messaging/src/main/java/com/izettle/messaging/handler/MessageDispatcher.java
izettle-messaging/src/test/java/com/izettle/messaging/handler/MessageDispatcherTest.java

MessageDispatcher will now check for handlers matching the Type value if no Subject is set on a
received message. This is useful for Amazon notifications as they lack Subject.

Check for handlers matching Type if no Subject set

---

izettle-cassandra-datastax/src/main/java/com/izettle/cassandra/SchemaVersionUpdaterWithDatastaxDriver.java

If the passed path parameter does not container `/` at the end, it will load files start with same name in resource dir.

Make sure use resource path as directory

---

izettle-messaging/src/main/java/com/izettle/messaging/QueueServiceSender.java
izettle-messaging/src/test/java/com/izettle/messaging/QueueServiceSenderTest.java

How about something like this, @calle? Thanks...

Check sendMessageBatch result, log if there are failures.

---

izettle-cassandra-astyanax/pom.xml
izettle-cassandra-datastax/pom.xml
izettle-dropwizard/src/main/java/com/izettle/dropwizard/cassandra/CassandraSessionFactory.java

Ping @ssprang, verified in test....

Tweak Cassandra driver settings.

---

izettle-cart/README.md

* Include info about ServiceCharge
* Some other clarifications
ping @MrShish or @karlgrund perhaps?

Documentation: Improve Cart README

---

izettle-dropwizard/pom.xml
izettle-jackson/pom.xml
izettle-messaging/pom.xml
pom.xml

Added <provided> to faster-xml stuff
https://izettle.atlassian.net/browse/SF-501

Update dependencies to newest version

---

izettle-dropwizard/src/main/java/com/izettle/dropwizard/cassandra/CassandraSessionFactory.java

1. Be explicit about Cassandra consistency level.
2. Prefer Local consistency level.
Ping @progre55 and @x1a0... Thanks...

Cassandra native driver QueryOptions tweak

---

izettle-cassandra-astyanax/pom.xml
izettle-cassandra-datastax/pom.xml
izettle-dropwizard/pom.xml
pom.xml

Ping @adamvoncorswant. No need to hurry though.

Upgrade Cassandra driver to 3.2.0 and some cleanup.

---

izettle-java/src/main/java/com/izettle/java/TimeZoneId.java

And remove a few outdated ones.
ping @olsson

TimeZoneId: Update with current zones

---

pom.xml

Adhering to new checkstyle rules.
ping @davidodelberg perhaps?

Summer Cleanup: Bump parent pom and get new code checks

---

izettle-cart/README.md
izettle-cart/src/main/java/com/izettle/cart/Cart.java

Small method clarification.
Also, reformatting README file to 80 characters width (no content change)
ping again @vincenthauser

Cart: Improve Documentation

---

izettle-cart/src/main/java/com/izettle/cart/Cart.java
izettle-cart/src/test/java/com/izettle/cart/AlterationTest.java

Second attempt. Now with tests!
@vincenthauser

Cart: `getAvailableItems` now returns the full list

---

izettle-cart/src/main/java/com/izettle/cart/AlterationCart.java
izettle-cart/src/test/java/com/izettle/cart/AlterationTest.java

As per request, ping @vincenthauser

Cart: Add getCartWideDiscountValue to AlterationCart

---

izettle-cart/src/main/java/com/izettle/cart/Item.java

Does this make things easier to understand @martinfridh or @rillard ?

Documentation: Slight javadoc clarification of `Item.getId`

---

izettle-filters/src/main/java/com/izettle/dropwizard/filters/AdminDirectAccessFilter.java

Updates documentation for changes made in https://github.com/iZettle/izettle-toolbox/commit/ddc1959f414ff374715e8681a247da471e22e99c

izettle-filters: Update rotten documentation

---

izettle-jackson/src/main/java/com/izettle/jackson/module/InstantRFC3339Module.java

Ping @joaxand. Thanks for spotting this, and sorry for any inconveniences. 😄 👍

Fix usage of StdDateFormat.
